version: '3.8'

services:
  app:
    build: 
      context: ../
      dockerfile: .devcontainer/Dockerfile
    networks:
      - workspace
    volumes:
      - ..:/app
    # Set workspace env variables
    environment:
      - ZDOTDIR=/app/.dotfiles
networks:
  workspace:
